language: cpp

sudo: true

os: linux

compiler:
  - gcc

before_install:
  # so that adjusted PATH propagates into sudo
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
  - sudo apt-get install flawfinder
  - sudo /bin/sh -c "echo /usr/local/lib > /etc/ld.so.conf.d/usrlocal.conf"
  - sudo ldconfig -v

install:
  - ./autogen.sh
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
  - ldd /usr/local/libexec/singularity/sexec

script:
  - make test
