language: go

sudo: required
dist: trusty

go:
  - "1.10.x"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - export PATH="${GOPATH}/bin:${PATH}"
  - dep ensure -vendor-only

install:
  - ./compile.sh --clean

script:
  - echo "Passed"
