language: go

sudo: required
dist: trusty

go:
  - "1.11"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev

matrix:
  include:
    - os: linux
    - os: linux
      env: OS_TYPE=centos OS_VERSION=6
    - os: linux
      env: OS_TYPE=centos OS_VERSION=7
    - os: osx
      osx_image: xcode10.1
      before_install:
        - # pass
      install:
        - ./mconfig
        - make -C builddir
        - sudo make -C builddir install
      script:
        - sw_vers
        - singularity version
        - singularity help
    - os: osx
      osx_image: xcode9.2
      before_install:
        - # pass
      install:
        - ./mconfig
        - make -C builddir
        - sudo make -C builddir install
      script:
        - sw_vers
        - singularity version
        - singularity help

services:
  - docker

before_install:
  - .travis/before_install

install:
  - # override the default go install target

script:
  - .travis/script
