language: cpp

sudo: true

os: linux

compiler:
  - gcc

before_install:
  # so that adjusted PATH propagates into sudo
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
  - sudo apt-get install flawfinder

script:
  - ./test.sh
