version: 2.1

defaults: &defaults
  working_directory: ~/go/singularity

vm_defaults: &vm_defaults
  <<: *defaults
  machine:
    image: ubuntu-1604:201903-01

x-run:
  setup_environment: &setup_environment
    name: Setup environment
    command: |-
      echo 'set -x' >> $BASH_ENV
      echo 'export GOPATH=$HOME/go'           >> $BASH_ENV
      echo 'export GOROOT=/usr/local/go' >> $BASH_ENV
      echo 'export GOBIN=$HOME/go/bin'        >> $BASH_ENV
      echo 'export PATH=$GOBIN:$GOROOT/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin' >> $BASH_ENV
      env | sed -e 's,^,ENV: ,' | sort
      test -e $BASH_ENV && sed -e 's,^,BASH_ENV: ,' < $BASH_ENV

  update_go: &update_go
    name: Update Go to 1.13.1
    working_directory: /tmp
    command: |-
      wget https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz
      sudo rm -rf $GOROOT
      sudo tar -C /usr/local -xzf go1.13.1.linux-amd64.tar.gz
      sudo ln -s $GOROOT/bin/go /usr/local/bin/go

  fetch_deb_deps: &fetch_deb_deps
    name: Fetch deps
    working_directory: /tmp
    command: |-
      # https://discuss.circleci.com/t/could-not-get-lock-var-lib-apt-lists-lock/28337/4
      sudo killall -9 apt-get || true && \
      sudo apt-get update -y && \
      sudo apt-get install -y build-essential squashfs-tools libseccomp-dev cryptsetup

  build_singularity: &build_singularity
    name: Build Singularity
    command: |-
      ./mconfig -v -p /usr/local
      make -C ./builddir all

  check_singularity: &check_singularity
    name: Check Singularity
    command: |-
      make -C ./builddir check

  install_singularity: &install_singularity
    name: Install Singularity
    command: |-
      sudo make -C ./builddir install

  check_changes: &check_changes
    name: Check changes
    command: |-
      rc=0
      scripts/should-e2e-run "${CIRCLE_PROJECT_USERNAME}" "${CIRCLE_PROJECT_REPONAME}" "${CIRCLE_BRANCH}" "${CIRCLE_PULL_REQUEST}" || rc=$?
      case $rc in
        0)
          echo "Verifying critical changes"
          ;;

        1)
          echo "No critical changes, skipping tests"
          circleci step halt
          ;;

        *)
          echo "E: scripts/should-e2e-run returned with exit code $rc. Abort."
          exit $rc
          ;;
      esac

jobs:
  check_go_mod:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run:
          name: Check go.mod
          command: scripts/check-go.mod

  go113-stretch:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.13.1-stretch
    steps:
      - checkout
      - run:
          <<: *build_singularity
      - run:
          <<: *check_singularity

  go113-alpine:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.13.1-alpine
    steps:
      - checkout
      - run:
          <<: *build_singularity
      - run:
          <<: *check_singularity

  go113-macos:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/go/src/github.com/sylabs/singularity
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |-
            echo 'export GOPATH=$HOME/go'      >> $BASH_ENV
            echo 'export GOROOT=/usr/local/go' >> $BASH_ENV
            echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> $BASH_ENV
      - run:
          name: Update Go to 1.13.1
          working_directory: /tmp
          command: |-
            curl -LO https://dl.google.com/go/go1.13.1.darwin-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.13.1.darwin-amd64.tar.gz
            sudo ln -s /usr/local/go/bin/go /usr/local/bin/go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -v -p /usr/local
            make -C ./builddir all
      - run:
          name: Check code
          command: |-
            make -C ./builddir check

  unit_tests:
    <<: *vm_defaults
    steps:
      - checkout
      - run:
          <<: *setup_environment
      - run:
          <<: *update_go
      - run:
          <<: *fetch_deb_deps
      - run:
          <<: *build_singularity
      - run:
          <<: *install_singularity
      - run:
          name: Run unit tests
          command: |-
            make -C ./builddir unit-test

  short_integration_tests:
    <<: *vm_defaults
    steps:
      - checkout
      - run:
          <<: *setup_environment
      - run:
          <<: *check_changes
      - run:
          <<: *update_go
      - run:
          <<: *fetch_deb_deps
      - run:
          <<: *build_singularity
      - run:
          <<: *install_singularity
      - run:
          name: Run short integration tests
          no_output_timeout: 20m
          command: |-
            make -C ./builddir short-integration-test

  e2e_tests:
    <<: *vm_defaults
    steps:
      - checkout
      - run:
          <<: *setup_environment
      - run:
          <<: *check_changes
      - run:
          <<: *update_go
      - run:
          <<: *fetch_deb_deps
      - run:
          <<: *build_singularity
      - run:
          <<: *install_singularity
      - run:
          name: Run E2E tests
          no_output_timeout: 35m
          command: |-
            export E2E_PARALLEL=8 && make -C ./builddir e2e-test
      - store_artifacts:
          path: builddir/e2e-cmd-report.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - go113-stretch
      - go113-alpine
      - go113-macos
      - check_go_mod
      - unit_tests
      - short_integration_tests
      - e2e_tests
